#!/usr/bin/env python3

"""Programme Name.

Usage:
  programme_name hello
  programme_name -h | --help
  programme_name --version

Options:
  -h --help     Show this screen.
  --version     Show version.

"""

from inspect import getmembers, isclass

from lib.docopt import docopt


if __name__ == '__main__':
    import commands
    options = docopt(__doc__, version='Programme Name 1.0')
    
    # Here we'll try to dynamically match the command the user is trying to run
    # with a pre-defined command class we've already created.
    for (k, v) in options.items(): 
        if hasattr(commands, k) and v:
            module = getattr(commands, k)
            commands = getmembers(module, isclass)
            command = [command[1] for command in commands if command[0] != 'Base'][0]
            command = command(options)
command.run()
